# This is a Makefile fragment (utils), see webp/src

SRC_DIRS += $(WEBPSRC)/utils

LIB_SRCS += bit_reader.c
LIB_SRCS += bit_writer.c
LIB_SRCS += color_cache.c
LIB_SRCS += filtersutils.c
LIB_SRCS += huffman.c
LIB_SRCS += huffman_encode.c
LIB_SRCS += quant_levels.c
LIB_SRCS += quant_levels_dec.c
LIB_SRCS += random.c
LIB_SRCS += rescalerutils.c
LIB_SRCS += thread.c
LIB_SRCS += utils.c
