# This is a Makefile fragment (base), see ttf/src/Makefile.
SRC_DIRS += $(SRC)/base

LIB_SRCS += ftbase.c
LIB_SRCS += ftbbox.c
LIB_SRCS += ftbitmap.c
LIB_SRCS += ftfntfmt.c
LIB_SRCS += ftfstype.c
LIB_SRCS += ftgasp.c
LIB_SRCS += ftglyph.c
LIB_SRCS += ftgxval.c
LIB_SRCS += ftinit.c
LIB_SRCS += ftlcdfil.c
LIB_SRCS += ftmm.c
LIB_SRCS += ftotval.c
LIB_SRCS += ftpatent.c
LIB_SRCS += ftpfr.c
LIB_SRCS += ftstroke.c
LIB_SRCS += ftsynth.c
LIB_SRCS += ftsystem.c
LIB_SRCS += fttype1.c
LIB_SRCS += ftwinfnt.c
LIV_RCS += ttf.rc
