TOP = ../../../..
include $(TOP)/configure/CONFIG

INC += ft2build.h
INC += freetype/config/ftheader.h
INC += freetype/config/ftconfig.h
INC += freetype/config/ftoption.h
INC += freetype/config/ftstdlib.h
INC += freetype/freetype.h
INC += freetype/fttypes.h
INC += freetype/ftsystem.h
INC += freetype/ftimage.h
INC += freetype/fterrors.h
INC += freetype/ftmoderr.h
INC += freetype/fterrdef.h
INC += freetype/ftglyph.h
INC += freetype/ftoutln.h
INC += freetype/ftbbox.h

include $(TOP)/configure/RULES
