# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_SRC)/pvAccess

INC += channelProviderLocal.h
INC += pvCopyMonitor.h

DBD += registerChannelProviderLocal.dbd

LIBSRCS += channelProviderLocal.cpp
LIBSRCS += channelLocal.cpp
LIBSRCS += pvCopyMonitor.cpp
LIBSRCS += monitorFactory.cpp
LIBSRCS += registerChannelProviderLocal.cpp

