# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_SRC)/pvAccess

INC += channelProviderLocal.h

DBD += registerChannelProviderLocal.dbd

LIBSRCS += channelProviderLocal.cpp
LIBSRCS += channelLocal.cpp
LIBSRCS += monitorFactory.cpp
LIBSRCS += registerChannelProviderLocal.cpp

