set NUMPUMPS=6
set BAUD=19200
set NoOfPZD=6

set ASYNPORT=TT

set ASYNPORT1=TT:01
set COMPORT1=COM1

set ASYNPORT2=TT:02
set COMPORT2=COM2

set ASYNPORT3=TT:03
set COMPORT3=COM3

set ASYNPORT4=TT:04
set COMPORT4=COM4

set ASYNPORT5=NT:07
set COMPORT5=COM7

set ASYNPORT6=NT:07
set COMPORT5=COM10


..\Release_LIB\LeyboldTurboApp ..\iocBoot\iocLeyboldTurbo\st6.cmd
