#!/bin/bash
#!-*- sh -*-
#
# Copyright: See the COPYRIGHT that is included with this distribution.
#            EPICS exampleCPP is distributed subject to a Software License
#            Agreement found in file LICENSE that is included with this
#            distribution.
#
# Abs: helloClientRunner executes the helloWorldClient EV4 client.
#
# Rem: helloWorldClient is a simple example of an E4C client demonstrating support
#      for a client/server environment in EPICS V4. 
#
#      helloWorldClient passes the argument it was given to the helloServer,
#      which constructs and returns a simple greeting. The helloClient receives 
#      the greeting, and prints it.
#
# Usage: Execute helloClientRunner any time while helloServerRunner is running.   
# 
#         > ./helloClientRunner [optional name, if not supplied, "Dave" is used].  
#
#         E.g.: 
#         bash-3.2$ ./helloClientRunner julie
#         Hello julie
# 
# Ref: 
# ----------------------------------------------------------------------------
# Auth: 17-Jan-2013, Dave Hickin (david.hickin@diamond.ac.uk)
#
# ============================================================================

TOP=$(dirname $0)

$TOP/bin/$EPICS_HOST_ARCH/HelloClient ${1:-Dave}
