#!/bin/bash
#!-*- sh -*-
#
# Copyright: See the COPYRIGHT that is included with this distribution.
#            EPICS exampleCPP is distributed subject to a Software License
#            Agreement found in file LICENSE that is included with this
#            distribution.
#
# Abs: start_server starts the channel archiver service, which can query a
#      Channel Archiver index file, with a given service name 
#
# Rem: The Channel Archiver Service is an example of an EPICS v4 RPC service.
# 
#
# Usage:  Execute helloServerRunner prior to executing helloClientRunner. 
# 
#         > ./helloServerRunner          
# 
# ----------------------------------------------------------------------------
# Auth: 17-Jan-2013, Dave Hickin (david.hickin@diamond.ac.uk)
# ============================================================================

TOP=$(dirname $0)

$TOP/bin/$EPICS_HOST_ARCH/HelloService

