
# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_TEST)/src

TESTPROD_HOST += testPVCopy
testPVCopy_SRCS += testPVCopy.cpp
testHarness_SRCS += testPVCopy.cpp
TESTS += testPVCopy

TESTPROD_HOST += testPVRecord
testPVRecord_SRCS += testPVRecord.cpp
testHarness_SRCS += testPVRecord.cpp
TESTS += testPVRecord

TESTPROD_HOST += testExampleRecord
testExampleRecord_SRCS += testExampleRecord.cpp
testHarness_SRCS += testExampleRecord.cpp
TESTS += testExampleRecord


