copy EXAMPLE_CONFIG_SITE.local                                  CONFIG_SITE.local
copy EXAMPLE_CONFIG_SITE.local.Linux                            CONFIG_SITE.local.Linux
copy EXAMPLE_CONFIG_SITE.local.WIN32                            CONFIG_SITE.local.WIN32
copy EXAMPLE_CONFIG_SITE.local.darwin-x86                       CONFIG_SITE.local.darwin-x86
copy EXAMPLE_CONFIG_SITE.local.linux-x86                        CONFIG_SITE.local.linux-x86
copy EXAMPLE_CONFIG_SITE.local.linux-x86.vxWorks-ppc32          CONFIG_SITE.local.linux-x86.vxWorks-ppc32
copy EXAMPLE_CONFIG_SITE.local.linux-x86.win32-x86-mingw        CONFIG_SITE.local.linux-x86.win32-x86-mingw
copy EXAMPLE_CONFIG_SITE.local.linux-x86.win32-x86-mingw-static CONFIG_SITE.local.linux-x86.win32-x86-mingw-static
copy EXAMPLE_CONFIG_SITE.local.linux-x86_64                     CONFIG_SITE.local.linux-x86_64
copy EXAMPLE_CONFIG_SITE.local.linux-x86_64-gcc42               CONFIG_SITE.local.linux-x86_64-gcc42

copy EXAMPLE_RELEASE.local                                      RELEASE.local
copy EXAMPLE_RELEASE.local.APS_Jenkins                          RELEASE.local.APS_Jenkins
copy EXAMPLE_RELEASE.local.linux-x86                            RELEASE.local.linux-x86
copy EXAMPLE_RELEASE.local.linux-x86_64                         RELEASE.local.linux-x86_64
copy EXAMPLE_RELEASE.local.win32-x86                            RELEASE.local.win32-x86
copy EXAMPLE_RELEASE_BASE.local.win32-x86                       RELEASE_BASE.local.win32-x86
copy EXAMPLE_RELEASE_SUPPORT.local                              RELEASE_SUPPORT.local
copy EXAMPLE_RELEASE_SUPPORT.local.win32-x86                    RELEASE_SUPPORT.local.win32-x86
copy EXAMPLE_RELEASE_LIBS.local                                 RELEASE_LIBS.local
copy EXAMPLE_RELEASE_PRODS.local                                RELEASE_PRODS.local
