# This is a Makefile fragment (jpc), see libJasper/Makefile.

SRC_DIRS += $(LIBJASPER)/jpc

LIB_SRCS += jpc_bs.c
LIB_SRCS += jpc_cs.c
LIB_SRCS += jpc_dec.c
LIB_SRCS += jpc_enc.c
LIB_SRCS += jpc_math.c
LIB_SRCS += jpc_mct.c
LIB_SRCS += jpc_mqcod.c
LIB_SRCS += jpc_mqdec.c
LIB_SRCS += jpc_mqenc.c
LIB_SRCS += jpc_qmfb.c
LIB_SRCS += jpc_t1cod.c
LIB_SRCS += jpc_t1dec.c
LIB_SRCS += jpc_t1enc.c
LIB_SRCS += jpc_t2cod.c
LIB_SRCS += jpc_t2dec.c
LIB_SRCS += jpc_t2enc.c
LIB_SRCS += jpc_tagtree.c
LIB_SRCS += jpc_tsfb.c
LIB_SRCS += jpc_util.c

