# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVASRV_SRC)/dbPv

DBD += dbPv.dbd

INC += dbPv.h
INC += dbPvDebug.h
INC += caMonitor.h
INC += caSecurity.h

LIBSRCS += caContext.cpp
LIBSRCS += dbUtil.cpp
LIBSRCS += caMonitor.cpp
LIBSRCS += caSecurity.cpp
LIBSRCS += dbPv.cpp
LIBSRCS += dbPvProvider.cpp
LIBSRCS += dbPvProcess.cpp
LIBSRCS += dbPvGet.cpp
LIBSRCS += dbPvMultiGet.cpp
LIBSRCS += dbPvPut.cpp
LIBSRCS += dbPvMultiPut.cpp
LIBSRCS += dbPvArray.cpp
LIBSRCS += dbPvRegister.cpp
LIBSRCS += dbPvMonitor.cpp
