# Db Makefile for example_EdwardsNextTurbo
#
TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# In a Diamond IOC Application, build db files from
# template files like this
#
DB += example_EdwardsNextTurbo.db
#DB += example_EdwardsNextTurbo_sim.db

USES_TEMPLATE += $(EDWARDSNEXTTURBO)/db/EdwardsNextTurbo.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
