TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


PROD_HOST += examplePvaClientProcess
examplePvaClientProcess_SRCS += examplePvaClientProcess.cpp
examplePvaClientProcess_LIBS += pvaClient pvAccess pvData ca Com


PROD_HOST += examplePvaClientGet
examplePvaClientGet_SRCS += examplePvaClientGet.cpp
examplePvaClientGet_LIBS += pvaClient pvAccess pvData ca Com

PROD_HOST += examplePvaClientPut
examplePvaClientPut_SRCS += examplePvaClientPut.cpp
examplePvaClientPut_LIBS += pvaClient pvAccess pvData ca Com


PROD_HOST += examplePvaClientMonitor
examplePvaClientMonitor_SRCS += examplePvaClientMonitor.cpp
examplePvaClientMonitor_LIBS += pvaClient pvAccess pvData ca Com


PROD_HOST += examplePvaClientMultiDouble
examplePvaClientMultiDouble_SRCS += examplePvaClientMultiDouble.cpp
examplePvaClientMultiDouble_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += examplePvaClientNTMulti
examplePvaClientNTMulti_SRCS += examplePvaClientNTMulti.cpp
examplePvaClientNTMulti_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += helloWorldRPC
helloWorldRPC_SRCS += helloWorldRPC.cpp
helloWorldRPC_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += helloWorldPutGet
helloWorldPutGet_SRCS += helloWorldPutGet.cpp
helloWorldPutGet_LIBS += pvaClient pvAccess nt pvData ca Com

PROD_HOST += monitorForever
monitorForever_SRCS += monitorForever.cpp
monitorForever_LIBS += pvaClient pvAccess nt pvData ca Com

PROD_HOST += getForever
getForever_SRCS += getForever.cpp
getForever_LIBS += pvaClient pvAccess nt pvData ca Com

PROD_HOST += putUnionForever
putUnionForever_SRCS += putUnionForever.cpp
putUnionForever_LIBS += pvaClient pvAccess nt pvData ca Com

PROD_HOST += testRAII
testRAII_SRCS += testRAII.cpp
testRAII_LIBS += pvaClient pvAccess nt pvData ca Com

PROD_HOST += testRAIIMultiDouble
testRAIIMultiDouble_SRCS += testRAIIMultiDouble.cpp
testRAIIMultiDouble_LIBS += pvaClient pvAccess nt pvData ca Com


PROD_HOST += testRAIINTMulti
testRAIINTMulti_SRCS += testRAIINTMulti.cpp
testRAIINTMulti_LIBS += pvaClient pvAccess nt pvData ca Com


#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

