/* Generated file errSymTbl.c */

#include "errMdef.h"
#include "errSymTbl.h"
#include "dbDefs.h"


static ERRSYMBOL symbols[] = {
    { (M_devLib| 1), "interrupt vector in use"},
    { (M_devLib| 2), "interrupt vector install failed"},
    { (M_devLib| 3), "Unrecognized interrupt type"},
    { (M_devLib| 4), "Interrupt vector not in use by caller"},
    { (M_devLib| 5), "Invalid VME A16 address"},
    { (M_devLib| 6), "Invalid VME A24 address"},
    { (M_devLib| 7), "Invalid VME A32 address"},
    { (M_devLib| 8), "Unrecognized address space type"},
    { (M_devLib| 9), "Specified device address overlaps another device"},
    { (M_devLib| 10), "This device already owns the address range"},
    { (M_devLib| 11), "unable to map address"},
    { (M_devLib| 12), "Interrupt at vector disconnected from an EPICS device"},
    { (M_devLib| 13), "Internal failure"},
    { (M_devLib| 14), "unable to enable interrupt level"},
    { (M_devLib| 15), "unable to disable interrupt level"},
    { (M_devLib| 16), "Memory allocation failed"},
    { (M_devLib| 17), "Specified device address unregistered"},
    { (M_devLib| 18), "No device at specified address"},
    { (M_devLib| 19), "Wrong device type found at specified address"},
    { (M_devLib| 20), "Signal number (offset) to large"},
    { (M_devLib| 21), "Signal count to large"},
    { (M_devLib| 22), "Device does not support requested operation"},
    { (M_devLib| 23), "Parameter to high"},
    { (M_devLib| 24), "Parameter to low"},
    { (M_devLib| 25), "Specified address is ambiguous (more than one device responds)"},
    { (M_devLib| 26), "Device self test failed"},
    { (M_devLib| 27), "Device failed during initialization"},
    { (M_devLib| 28), "Input exceeds Hardware Limit"},
    { (M_devLib| 29), "Unable to locate address space for device"},
    { (M_devLib| 30), "device timed out"},
    { (M_devLib| 31), "bad function pointer"},
    { (M_devLib| 32), "bad interrupt vector"},
    { (M_devLib| 33), "bad function argument"},
    { (M_devLib| 34), "Invalid ISA address"},
    { (M_devLib| 35), "Invalid VME CR/CSR address"},
    { (M_asLib| 1), "Client Exists"},
    { (M_asLib| 2), "User Access Group does not exist"},
    { (M_asLib| 3), "Host Access Group does not exist"},
    { (M_asLib| 4), "access security: no access allowed"},
    { (M_asLib| 5), "access security: no modification allowed"},
    { (M_asLib| 6), "access security: bad configuration file"},
    { (M_asLib| 7), "access security: bad calculation espression"},
    { (M_asLib| 8), "Duplicate Access Security Group"},
    { (M_asLib| 9), "access security: Init failed"},
    { (M_asLib|10), "access security is not active"},
    { (M_asLib|11), "access security: bad ASMEMBERPVT"},
    { (M_asLib|12), "access security: bad ASCLIENTPVT"},
    { (M_asLib|13), "access security: bad ASG"},
    { (M_asLib|14), "access security: no Memory"},
    { (M_dbAccess| 1), "Process Variable Not Found"},
    { (M_dbAccess| 3), "Illegal Database Request Type"},
    { (M_dbAccess| 5), "Attempt to modify noMod field"},
    { (M_dbAccess| 7), "Illegal Lock Set"},
    { (M_dbAccess| 9), "get precision failed"},
    { (M_dbAccess|11), "Only one element allowed"},
    { (M_dbAccess|13), "Illegal choice"},
    { (M_dbAccess|15), "Illegal field value"},
    { (M_dbAccess|17), "Logic error generating lock sets"},
    { (M_dbAccess|21), "No link support table or entry"},
    { (M_dbAccess|31), "missing record support entry table"},
    { (M_dbAccess|33), "RSET or DSXT routine not defined"},
    { (M_dbAccess|35), "Subroutine not found"},
    { (M_dbAccess|37), "Request is pending"},
    { (M_dbAccess|39), "Request is Blocked"},
    { (M_dbAccess|41), "putFields are disabled"},
    { (M_dbAccess|43), "Hardware link type not on INP/OUT"},
    { (M_dbAccess|53), "Breakpoint already set"},
    { (M_dbAccess|55), "No breakpoint set in record"},
    { (M_dbAccess|57), "Record not stopped"},
    { (M_dbAccess|59), "Error in argument"},
    { (M_dbAccess|61), "Logic error in breakpoint routine"},
    { (M_dbAccess|63), "Cannot spawn dbContTask"},
    { (M_dbAccess|65), "Cannot resume dbContTask"},
    { (M_dbAccess|66), "unable to allocate data structure from pool"},
    { (M_dbAccess|67), "Not initialized"},
    { (M_dbAccess|68), "Buffer full"},
    { (M_devSup| 1), "SDR_DEVSUP: Device support missing"},
    { (M_devSup| 3), "Missing device support entry table"},
    { (M_devSup| 5), "Missing device support routine"},
    { (M_devSup| 7), "Bad INP link type"},
    { (M_devSup| 9), "Bad OUT link type"},
    { (M_devSup|11), "Bad init_rec return value"},
    { (M_devSup|13), "Illegal bus type"},
    { (M_devSup|15), "Illegal or nonexistant module"},
    { (M_devSup|17), "Illegal signal"},
    { (M_devSup|19), "No init"},
    { (M_devSup|21), "Multiple records accessing same signal"},
    { (M_devSup|23), "No device found at specified address"},
};

static ERRSYMTAB symTbl = {
    NELEMENTS(symbols), symbols
};

ERRSYMTAB_ID errSymTbl = &symTbl;

