# This is a Makefile fragment (base), see libJasper/Makefile.

SRC_DIRS += $(LIBJASPER)/base

LIB_SRCS += jas_cm.c
LIB_SRCS += jas_debug.c
LIB_SRCS += jas_getopt.c
LIB_SRCS += jas_icc.c
LIB_SRCS += jas_iccdata.c
LIB_SRCS += jas_image.c
LIB_SRCS += jas_init.c
LIB_SRCS += jas_malloc.c
LIB_SRCS += jas_seq.c
LIB_SRCS += jas_stream.c
LIB_SRCS += jas_string.c
LIB_SRCS += jas_tmr.c
LIB_SRCS += jas_tvp.c
LIB_SRCS += jas_version.c
LIB_RCS += jp2.rc
