# Boot Makefile for example_EdwardsNextTurbo
#
TOP = ../..
include $(TOP)/configure/CONFIG

SCRIPTS+=stexample_EdwardsNextTurbo.boot
SCRIPTS+=stexample_EdwardsNextTurbo_sim.boot
SCRIPTS+=../stexample_EdwardsNextTurbo_sim.sh

include $(TOP)/configure/RULES
