# This is a Makefile fragment (enc), see webp/src

SRC_DIRS += $(WEBPSRC)/enc

LIB_SRCS += vp8lenc.c
LIB_SRCS += treeenc.c
LIB_SRCS += token.c
LIB_SRCS += syntax.c
LIB_SRCS += near_lossless.c
LIB_SRCS += picture.c
LIB_SRCS += picture_csp.c
LIB_SRCS += picture_psnr.c
LIB_SRCS += picture_rescale.c
LIB_SRCS += picture_tools.c
LIB_SRCS += quantenc.c
LIB_SRCS += iterator.c
LIB_SRCS += histogram.c
LIB_SRCS += frameenc.c
LIB_SRCS += filter.c
LIB_SRCS += config.c
LIB_SRCS += costenc.c
LIB_SRCS += delta_palettization.c
LIB_SRCS += backward_references.c
LIB_SRCS += alphaenc.c
LIB_SRCS += analysis.c
LIB_SRCS += webpenc.c
