#!/bin/sh

source /home/epics/Startup/startup.R3.14.12.sh
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${EPICS_MODULES}/support/asyn/4-13/lib/${EPICS_HOST_ARCH}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${EPICS_MODULES}/support/sscan/2-6-6/lib/${EPICS_HOST_ARCH}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${EPICS_MODULES}/support/calc/2-8/lib/${EPICS_HOST_ARCH}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${EPICS_MODULES}/support/stream/2-4-1/lib/${EPICS_HOST_ARCH}"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${EPICS_LOCAL}/drivers/MoxaSerialMode/1-0/lib/${EPICS_HOST_ARCH}"

../../bin/linux-armv5teb/VarianTurboPump st.cmd
