# This is a Makefile fragment (dec), see webp/src

SRC_DIRS += $(WEBPSRC)/dec

LIB_SRCS += alphadec.c
LIB_SRCS += buffer.c
LIB_SRCS += framedec.c
LIB_SRCS += idec.c
LIB_SRCS += io.c
LIB_SRCS += quantdec.c
LIB_SRCS += treedec.c
LIB_SRCS += vp8.c
LIB_SRCS += vp8ldec.c
LIB_SRCS += webp.c
