TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testBoost 
#test_CXXFLAGS += -DPV_MB
testBoost_SRCS += testBoost.cpp
#testBoost_LIBS +=

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

