TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testBoost 
#test_CXXFLAGS += -DPV_MB
testBoost_SRCS += testBoost.cpp
USR_LDFLAGS += -LIBPATH:../../../boostApp/boost/stage/lib/
#testBoost_LIBS +=

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

