TOP=../..
include $(TOP)/configure/CONFIG
#---------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=======================================

LIBRARY_IOC_Linux = cbfad
LIBRARY_IOC_Darwin = cbfad
LIBRARY_IOC_solaris = cbfad

INC += cbf_ad.h
INC += cbf_tree_ad.h
INC += cbf_context_ad.h
INC += cbf_file_ad.h
INC += global_ad.h
INC += md5_ad.h

cbfad_SRCS += cbf.c
cbfad_SRCS += cbf_alloc.c
cbfad_SRCS += cbf_ascii.c
cbfad_SRCS += cbf_binary.c
cbfad_SRCS += cbf_byte_offset.c
cbfad_SRCS += cbf_canonical.c
cbfad_SRCS += cbf_codes.c
cbfad_SRCS += cbf_compress.c
cbfad_SRCS += cbf_context.c
cbfad_SRCS += cbf_file.c
cbfad_SRCS += cbf_getopt.c
cbfad_SRCS += cbf_lex.c
cbfad_SRCS += cbf_packed.c
cbfad_SRCS += cbf_predictor.c
cbfad_SRCS += cbf_read_binary.c
cbfad_SRCS += cbf_read_mime.c
cbfad_SRCS += cbf_simple.c
cbfad_SRCS += cbf_string.c
cbfad_SRCS += cbf_stx.c
cbfad_SRCS += cbf_tree.c
cbfad_SRCS += cbf_uncompressed.c
cbfad_SRCS += cbf_write.c
cbfad_SRCS += cbf_write_binary.c
cbfad_SRCS += cbf_ws.c
cbfad_SRCS += md5c.c

include $(TOP)/configure/RULES
#---------------------------------------
#  ADD RULES AFTER THIS LINE
#=======================================
