# This is a Makefile fragment (inc), see libJasper/Makefile.

SRC_DIRS += $(LIBJASPER)/inc

INC += jasper/jasper.h
INC += jasper/jas_config.h
INC += jasper/jas_config2.h
INC += jasper/jas_config.h
INC += jasper/jas_types.h
INC += jasper/jas_version.h
INC += jasper/jas_init.h
INC += jasper/jas_cm.h
INC += jasper/jas_icc.h
INC += jasper/jas_fix.h
INC += jasper/jas_debug.h
INC += jasper/jas_getopt.h
INC += jasper/jas_image.h
INC += jasper/jas_icc.h
INC += jasper/jas_math.h
INC += jasper/jas_malloc.h
INC += jasper/jas_seq.h
INC += jasper/jas_stream.h
INC += jasper/jas_string.h
INC += jasper/jas_tmr.h
INC += jasper/jas_tvp.h
