# This is a Makefile fragment, see src/Makefile.

SRC_DIRS += $(SRC)/VQM/CrossPlatform

VQM_ITMS_Dev_SRCS += GaugeDAQ.cpp
VQM_ITMS_Dev_SRCS += IServiceWrapper.cpp

DIRS += FIR-filter-class

INC += IServiceWrapper.h
INC += IHeaderData.h
INC += GaugeDAQ.h
INC += SVQM_800_Error.h
